export const ADMIN_GET_ALL_ROOMS_SUCCESS = "ADMIN_GET_ALL_ROOMS_SUCCESS";
export const ADMIN_GET_ALL_ROOMS_FAILED = "ADMIN_GET_ALL_ROOMS_FAILED";
export const ADMIN_GET_ALL_ROOMS_SERVER_ERR = "ADMIN_GET_ALL_ROOMS_SERVER_ERR";


export const ADD_ROOMS_SUCCESS = "ADD_ROOMS_SUCCESS";
export const ADD_ROOMS_FAILED = "ADD_ROOMS_FAILED";
export const ADD_ROOMS_LOADING = "ADD_ROOMS_LOADING";
export const ADD_ROOMS_SERVER_ERR = "ADD_ROOMS_SERVER_ERR";


export const UPDATE_ROOMS_SUCCESS = "UPDATE_ROOMS_SUCCESS";
export const UPDATE_ROOMS_FAILED = "UPDATE_ROOMS_FAILED";
export const UPDATE_ROOMS_LOADING = "UPDATE_ROOMS_LOADING";
export const UPDATE_ROOMS_SERVER_ERR = "UPDATE_ROOMS_SERVER_ERR";

export const DELETE_ROOMS_SUCCESS = "DELETE_ROOMS_SUCCESS";
export const DELETE_ROOMS_FAILED = "DELETE_ROOMS_FAILED";
export const DELETE_ROOMS_LOADING = "DELETE_ROOMS_LOADING";
export const DELETE_ROOMS_SERVER_ERR = "DELETE_ROOMS_SERVER_ERR";

export const GET_ALL_ADMIN_BOOKING_SUCCESS = "GET_ALL_ADMIN_BOOKING_SUCCESS";
export const GET_ALL_ADMIN_BOOKING_FAILED = "GET_ALL_ADMIN_BOOKING_FAILED";
export const GET_ALL_ADMIN_BOOKING_SERVER_ERR = "GET_ALL_ADMIN_BOOKING_SERVER_ERR";


export const GET_ADMIN_BOOK_SUCCESS = "GET_ADMIN_BOOK_SUCCESS";
export const GET_ADMIN_BOOK_FAILED = "GET_ADMIN_BOOK_FAILED";
export const GET_ADMIN_BOOK_SERVER_ERR = "GET_ADMIN_BOOK_SERVER_ERR";


export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAILED = "DELETE_BOOKING_FAILED";
export const DELETE_BOOKING_LOADING = "DELETE_BOOKING_LOADING";
export const DELETE_BOOKING_SERVER_ERR = "DELETE_BOOKING_SERVER_ERR";



export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILED = "GET_ALL_USER_FAILED";
export const GET_ALL_USER_SERVER_ERR = "GET_ALL_USER_SERVER_ERR";


export const USER_ADMIN_UPDATE_SUCCESS = "USER_ADMIN_UPDATE_SUCCESS";
export const USER_ADMIN_UPDATE_FAILED = "USER_ADMIN_UPDATE_FAILED";
export const USER_ADMIN_UPDATE_LOADING = "USER_ADMIN_UPDATE_LOADING";
export const USER_ADMIN_UPDATE_SERVER_ERR = "USER_ADMIN_UPDATE_SERVER_ERR";


export const USER_ADMIN_DELETE_SUCESS = "USER_ADMIN_DELETE_SUCESS";
export const USER_ADMIN_DELETE_FAILED = "USER_ADMIN_DELETE_FAILED";
export const USER_ADMIN_DELETE_SERVER_ERR = "USER_ADMIN_DELETE_SERVER_ERR";


export const GET_ADMIN_REVIEWS_SUCCESS = "GET_ADMIN_REVIEWS_SUCCESS";
export const GET_ADMIN_REVIEWS_FAILED = "GET_ADMIN_REVIEWS_FAILED";
export const GET_ADMIN_REVIEWS_SERVER_ERR = "GET_ADMIN_REVIEWS_SERVER_ERR";


export const DELETE_REVIEWS_SUCCESS = "DELETE_REVIEWS_SUCCESS";
export const DELETE_REVIEWS_FAILED = "DELETE_REVIEWS_FAILED";
export const DELETE_REVIEWS_SERVER_ERR = "DELETE_REVIEWS_SERVER_ERR";