export const CHECK_BOOKING_AVAILABLE_SUCCESS = "CHECK_BOOKING_AVAILABLE_SUCCESS";


export const GET_BOOKED_DATES_SUCCESS = "GET_BOOKED_DATES_SUCCESS";


export const GET_ALL_BOOKING_SUCCESS = "GET_ALL_BOOKING_SUCCESS";
export const GET_ALL_BOOKING_FAILED = "GET_ALL_BOOKING_FAILED";
export const GET_ALL_BOOKING_SERVER_ERR = "GET_ALL_BOOKING_SERVER_ERR";

export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAILED = "GET_BOOKING_FAILED";
export const GET_BOOKING_SERVER_ERR = "GET_BOOKING_SERVER_ERR";
