export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";
export const GET_REVIEWS_SEVRER_ERR = "GET_REVIEWS_SEVRER_ERR";


export const CHECK_REVIEWS_SUCCESS = "CHECK_REVIEWS_SUCCESS";
export const CHECK_REVIEWS_FAILED = "CHECK_REVIEWS_FAILED";
export const CHECK_REVIEWS_SERVER_ERR = "CHECK_REVIEWS_SERVER_ERR";


export const ADD_REVIEWS_SUCCESS = "ADD_REVIEWS_SUCCESS";
export const ADD_REVIEWS_FAILED = "ADD_REVIEWS_FAILED";
export const ADD_REVIEWS_LOADING = "ADD_REVIEWS_LOADING";
export const ADD_REVIEWS_SERVER_ERR = "ADD_REVIEWS_SERVER_ERR";


export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAILED = "UPDATE_REVIEW_FAILED";
export const UPDATE_REVIEW_LOADING = "UPDATE_REVIEW_LOADING";
export const UPDATE_REVIEW_SERVER_ERR = "UPDATE_REVIEW_SERVER_ERR";