export const ALL_ROOM_SUCCESS = "ALL_ROOM_SUCCESS";
export const ALL_ROOM_FAILED = "ALL_ROOM_FAILED";
export const ALL_ROOM_SERVER_ERROR = "ALL_ROOM_SERVER_ERROR";

export const ROOMS_BY_DHAKA_SUCCESS = "ROOMS_BY_DHAKA_SUCCESS";
export const ROOMS_BY_DHAKA_FAILED = "ROOMS_BY_DHAKA_FAILED";
export const ROOMS_BY_DHAKA_SERVER_ERROR = "ROOMS_BY_DHAKA_SERVER_ERROR";

export const ROOMS_BY_SYLHET_SUCCESS = "ROOMS_BY_SYLHET_SUCCESS";
export const ROOMS_BY_SYLHET_FAILED = "ROOMS_BY_SYLHET_FAILED";
export const ROOMS_BY_SYLHET_SERVER_ERROR = "ROOMS_BY_SYLHET_SERVER_ERROR";


export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS"
export const GET_ROOM_FAILED = "GET_ROOM_FAILED"
export const GET_ROOM_SERVER_ERR = "GET_ROOM_SERVER_ERR"