export const INITIAL_SEARCH_SUCCESS = "INITIAL_SEARCH_SUCCESS";

export const GET_ROOMS_BY_FIlTER_SUCCESS = "GET_ROOMS_BY_FIlTER_SUCCESS";
export const GET_ROOMS_BY_FILTER_FAILED = "GET_ROOMS_BY_FILTER_FAILED";
export const GET_ROOMS_BY_FILTER_SERVER_ERR = "GET_ROOMS_BY_FILTER_SERVER_ERR";