export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SERVER_ERR = "SIGNUP_SERVER_ERR";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SERVER_ERR = "GET_USER_SERVER_ERR";